name: CI/CD Pipeline - Dev

on:
  push:
    branches:
      - main

env:
  AWS_ACCOUNT: "578684999127"
  AWS_REGION: "us-east-1"
  APP_NAME: "linuxtips-app"
  CLUSTER_NAME: "linuxtips-ecs"
  REPOSITORY_NAME: "linuxtips/$APP_NAME"

jobs:
  ci-app:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Install GoLint
      run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.59.1

    - name: Lint App
      run: golangci-lint run ./... -E errcheck
      working-directory: ./app
    
    - name: Test App
      run: go test -v ./...
      working-directory: ./app

  ci-terraform:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.13.1"

    - name: Terraform fmt check
      run: terraform fmt --recursive --check
      working-directory: ./terraform

    - name: Terraform Init
      run: terraform init 
      working-directory: ./terraform
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION:  ${{ env.AWS_REGION }}

    - name: Terraform Validate
      run: terraform validate
      working-directory: ./terraform
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION:  ${{ env.AWS_REGION }}
